elasticsearch:
  home: C:\opt\elasticsearch-5.6.10
  hostname: localhost
  port: 9300
  cluster:
    name: elasticsearch

async:
  corePoolSize: 3
  maxPoolSize: 3
  queueCapacity: 100

scheduler:
  cron: 0 0 12 ? * *